In [1]:
!pip install numpy


In [2]:
import numpy as np

## CREATE ARRAY USING NUMPY

In [7]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## reshaping


arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 colums

array([[1, 2, 3, 4, 5]])

In [10]:
## nested list

arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## @D array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2) 
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [14]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## IDENTITY MATRIX

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(1)

array([[1.]])

In [21]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print( arr)

[[1 2 3]
 [4 5 6]]


In [24]:
print( arr.shape) 

(2, 3)


In [ ]:
print( arr.ndim) 

In [25]:
print(arr.size) 

6


In [26]:
print( arr.dtype)  

int64


In [27]:
print( arr.itemsize) 

8


## NUMPY VECTORIZED OPERATOR

In [31]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])


## element wise addition
print("Addition:",arr1+arr2)


## element wise substraction
print("substraction:",arr1-arr2)



## element wise multiplication
print("multiplication:",arr1*arr2)



## element wise division
print("division:",arr1/arr2)


Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [33]:
##universal functions---applied to entire array

arr=np.array([1,2,3,4,5])
print(np.sqrt(arr))    ## square root

print(np.exp(arr))    ## exponential

print(np.sin(arr))   ## sine

print(np.log(arr))  ## natural log

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [34]:
## array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
arr[0]

array([1, 2, 3, 4])

In [36]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)
print(arr[0][0])

print(arr[0:2,2:])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[3 4]
 [7 8]]


In [46]:
##to get  6 7 10 11

print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [47]:
## Modify array elements:

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [49]:
## logical operation

data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [52]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [53]:
data[(data>5) &(data<8)]

array([6, 7])